test

diff --git a/.github/workflows/jira-notification.yaml b/.github/workflows/jira-notification.yaml
--- a/.github/workflows/jira-notification.yaml
+++ b/.github/workflows/jira-notification.yaml
@@ -21,48 +21,59 @@ jobs:
       - name: print tag
         run: |
             yes | sudo apt-get install jq
-            response=$(curl --request POST \
-            --url 'https://nuamexchange.atlassian.net/rest/api/3/issue/issue/comment' \
-            --user 'alexander.rodriguez@nuamx.com:ATATT3xFfGF0dwDeafN1Cp6prAackBIZDW5cSaRhY8xzqtfLZnm6HAg2EamenpuD8qOvO_m3m8DDp23awhYJkYMHYtms5skbWsyMTv1v3ZTIVPWQNfEgPtwNzjYthaRrY42r4MzpO1zDHF-2sDW0uXeFDcYRq1w4Yj9b7Y9ZSkxztL5yNuJ4s2A=9D0D6595' \
-            --header 'Accept: application/json' \
-            --header 'Content-Type: application/json' \
-            --data '{
-                "body": {
-                    "content": [
-                    {
-                        "type": "panel",
-                        "attrs": {
-                        "panelType": "error"
-                        },
+
+            function send_notification {
+            
+                response=$(curl --request POST \
+                --url 'https://nuamexchange.atlassian.net/rest/api/3/issue/issue/comment' \
+                --user 'alexander.rodriguez@nuamx.com:ATATT3xFfGF0dwDeafN1Cp6prAackBIZDW5cSaRhY8xzqtfLZnm6HAg2EamenpuD8qOvO_m3m8DDp23awhYJkYMHYtms5skbWsyMTv1v3ZTIVPWQNfEgPtwNzjYthaRrY42r4MzpO1zDHF-2sDW0uXeFDcYRq1w4Yj9b7Y9ZSkxztL5yNuJ4s2A=9D0D6595' \
+                --header 'Accept: application/json' \
+                --header 'Content-Type: application/json' \
+                --data '{
+                    "body": {
                         "content": [
-                            {
-                                "type": "heading",
-                                "attrs": {
-                                    "level": 2
+                        {
+                            "type": "panel",
+                            "attrs": {
+                            "panelType": "error"
+                            },
+                            "content": [
+                                {
+                                    "type": "heading",
+                                    "attrs": {
+                                        "level": 2
+                                    },
+                                    "content": [
+                                    {
+                                        "type": "text",
+                                        "text": "texto"
+                                    }
+                                    ]
                                 },
+                            {
+                                "type": "paragraph",
                                 "content": [
                                 {
                                     "type": "text",
                                     "text": "texto"
                                 }
                                 ]
-                            },
-                        {
-                            "type": "paragraph",
-                            "content": [
-                            {
-                                "type": "text",
-                                "text": "texto"
                             }
                             ]
                         }
-                        ]
-                    }
-                    ],
-                    "type": "doc",
-                    "version": 1
-                    }
-                }')
+                        ],
+                        "type": "doc",
+                        "version": 1
+                        }
+                    }')
+            }
+
+            code=$?
+            if [ $code -ne 0 ]; then
+                echo "An error ocurred"
+                exit 0
+            fi
+
             echo "respuesta : $response"
             if [ $? -ne 0 ]; then
                 echo "Error: No se pudo hacer petición"
