test

diff --git a/.github/workflows/jira-notification.yaml b/.github/workflows/jira-notification.yaml
--- a/.github/workflows/jira-notification.yaml
+++ b/.github/workflows/jira-notification.yaml
@@ -72,12 +72,12 @@ jobs:
 
             send_notification
 
-            # if [ $? -ne 0 ]; then
-            #     echo "Error: No se pudo hacer petición"
-            #     echo "respuesta : $response"
-            #     exit 0
-            # fi
-            # if grep -q '"errorMessages":' <<< "$response"; then
-            #     error_messages=$(echo "$response" | jq -r '.errorMessages[]')
-            #     echo "$error_messages"
-            # fi
+            if [ $? -ne 0 ]; then
+                echo "Error: No se pudo hacer petición"
+                echo "respuesta : $response"
+                exit 0
+            fi
+            if grep -q '"errorMessages":' <<< "$response"; then
+                error_messages=$(echo "$response" | jq -r '.errorMessages[]')
+                echo "$error_messages"
+            fi
